#!/usr/bin/env bash
set -e # halt script on error

# network environment info
curl -s http://whatismyip.akamai.com | xargs echo "IP: "
dig whoami.akamai.net +short | xargs echo "whoami: "

# Akamai CLI
curl -OL "https://github.com/akamai/cli/releases/download/1.0.2/akamai-1.0.2-linuxamd64"
chmod +x akamai-1.0.2-linuxamd64
mv akamai-1.0.2-linuxamd64 /tmp/akamai

bundle exec jekyll b -c _config.yml

# External Link checking only
# bundle exec htmlproofer ./_site --disable-external --alt-ignore '/.*/' --allow-hash-href true

# External Link and image checking
# bundle exec htmlproofer ./_site/ --alt-ignore '/.*/' --allow-hash-href true --http-status-ignore 0,301,302,403,999 --check-img-http
